name: Projects

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "projects"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-southeast-2"

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: List directory contents
        run: ls -la .

      - name: Initialise terraform state (website)
        working-directory: terraform/website/upload
        run: terraform init

      - name: Apply terraform state (website)
        working-directory: terraform/website/upload
        run: terraform apply -auto-approve
      - name: Initialise terraform state (rust-chat-room)
        working-directory: terraform/rust-chat-room
        run: terraform init

      - name: Apply terraform state (rust-chat-room)
        working-directory: terraform/rust-chat-room
        run: terraform apply -auto-approve
